include('../../../../config-service/Tiltfile')
include('../../../../catalog-service/Tiltfile')
include('../../../../order-service/Tiltfile')
include('../../../../polar-edge-service/Tiltfile')

update_settings(max_parallel_updates=1)